- name: Install OpenSSH server
  become: true
  apt:
    name: openssh-server


- name: Ensure user exists
  user:
    name: "{{ user }}"

- name: Ensure ~/.ssh directory exists
  become: true
  become_user: "{{ user }}"
  file:
    path: /home/{{ user }}/.ssh/
    owner: "{{ user }}"
    group: "{{ user }}"
    state: directory


- name: Install authorized_keys
  become: true
  become_user: "{{ user }}"
  template:
    src: templates/authorized_keys
    dest: /home/{{ user }}/.ssh/authorized_keys

- name: Only allow public key authentication
  become: true
  blockinfile:
    dest: /etc/ssh/sshd_config
    block: |
      AllowUsers {{ user }}
      PubkeyAuthentication yes
      PasswordAuthentication no

- name: Reload sshd
  become: true
  service:
    name: ssh
    state: reloaded
  # May fail during preseed
  ignore_errors: yes

- name: Enable NOPASSWD sudo access
  become: true
  lineinfile:
    dest: /etc/sudoers
    line: "{{ user }} ALL=(ALL) NOPASSWD: ALL"


# Zerotier-one

- name: Add zerotier gpg key to apt
  become: true
  apt_key:
    id: 23E52A61
    url: https://www.zerotier.com/misc/contact@zerotier.com.gpg

- name: Add zerotier apt repository
  become: true
  apt_repository:
    repo: deb http://download.zerotier.com/debian/xenial xenial main

- name: Install zerotier-one
  become: true
  apt:
    name: zerotier-one

- name: Enable and start zerotier service
  become: true
  service:
    name: zerotier-one
    enabled: yes
    state: started
  # May fail during preseed
  ignore_errors: true

- name: Join ZeroTier network
  become: true
  shell: zerotier-cli join {{ zerotier_network_id }}
  # May fail during preseed
  ignore_errors: true

- name: Join ZeroTier network on reboot
  become: true
  cron:
    name: "join Dividat ZeroTier network"
    special_time: reboot
    state: present
    job: /bin/sleep 30 ; /usr/sbin/zerotier-cli join {{ zerotier_network_id }}

- name: Remove init scripts to join ZeroTier network (deprecated by cron job at @reboot) (1/2)
  become: true
  file:
    path: /etc/rc2.d/S99join-zerotier-network
    state: absent

- name: Remove init scripts to join ZeroTier network (deprecated by cron job at @reboot) (2/2)
  become: true
  file:
    path: /etc/init.d/join-zerotier-network
    state: absent
