- name: Remove deprecated zesty repositories
  become: true
  apt_repository:
    repo: "{{ item }}"
    state: absent
    update_cache: no
  with_items:
    - "deb http://ubuntu.ethz.ch/ubuntu/ zesty-security universe"
    - "deb http://ubuntu.ethz.ch/ubuntu/ zesty-security multiverse"
    - "deb http://ubuntu.ethz.ch/ubuntu/ zesty main restricted"
    - "deb http://ubuntu.ethz.ch/ubuntu/ zesty-updates main restricted"
    - "deb http://ubuntu.ethz.ch/ubuntu/ zesty universe"
    - "deb http://ubuntu.ethz.ch/ubuntu/ zesty-updates universe"
    - "deb http://ubuntu.ethz.ch/ubuntu/ zesty multiverse"
    - "deb http://ubuntu.ethz.ch/ubuntu/ zesty-updates multiverse"
    - "deb http://ubuntu.ethz.ch/ubuntu/ zesty-backports main restricted universe multiverse"
    - "deb http://ubuntu.ethz.ch/ubuntu/ zesty-backports main restricted universe multiverse"
    - "deb http://ubuntu.ethz.ch/ubuntu/ zesty-security main restricted"

- name: Add legacy zesty repositories
  when: ansible_distribution_version == '17.04'
  become: true
  apt_repository:
    repo: "{{ item }}"
    state: present
    update_cache: no
  with_items:
    - "deb http://old-releases.ubuntu.com/ubuntu/ zesty main restricted universe multiverse"
    - "deb http://old-releases.ubuntu.com/ubuntu/ zesty-updates main restricted universe multiverse"
    - "deb http://old-releases.ubuntu.com/ubuntu/ zesty-security main restricted universe multiverse"

- name: "Install aptitude"
  raw: apt-get install -y aptitude
  become: true

- name: Upgrade packages
  become: true
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400 #One day
  ignore_errors: true

# This fixes issues that NetworkManager does not manage devices
- name: Make Network Manager manage connections (1/3)
  become: true
  template:
    src: templates/NetworkManager.conf
    dest: /etc/NetworkManager/NetworkManager.conf

# The network installer automatically  adds the primary network interface to network interfaces as auto. This will cause systemd to wait for device on booot (for 5 minutes!). By deleting all entries we set all devices in "hotplug" mode.
- name: Make Network Manager manage connections (2/3)
  become: true
  template:
    src: templates/interfaces
    dest: /etc/network/interfaces

- name: Make Network Manager manage connections (3/3)
  become: true
  file:
    path: /etc/NetworkManager/conf.d/10-globally-managed-devices.conf
    state: touch

- name: Disable update manager
  become: true
  apt:
    name: update-manager
    state: absent
