- name: Logout Play user
  become: true
  shell: skill -KILL -u play && sleep 10
  when: clean_all_play_data

- name: Cleanup
  become: true
  user:
    name: play
    state: absent
    remove: yes
  when: clean_all_play_data

- name: Add nopasswdlogin group
  become: true
  group:
    name: nopasswdlogin
    state: present

- name: Add play user
  become: true
  user:
    name: play
    comment: "Dividat Play"
    password: $6$Ev6hoX3w$RaWbeHNXmnir0l5yMfgGuItQ3WkQoR0LZnhVg6m4vJ461vrPpZG.ZORmmIr5BF6Qm6gVE8ADa8fOx3eBRMjUE1
    groups: nopasswdlogin

- name: Install Chromium
  become: true
  apt:
    name: chromium-browser

- name: Ensure ~/bin directory exists
  become: true
  file:
    path: /home/play/bin/
    owner: play
    group: play
    state: directory

- name: Add play-kiosk script
  become: true
  template:
    src: templates/play-kiosk.sh
    dest: /home/play/bin/play-kiosk.sh
    owner: play
    group: play
    mode: u+x

- name: Ensure ~/.local/share/keyrings directory exists
  become: true
  file:
    path: /home/play/.local/share/keyrings
    owner: play
    group: play
    state: directory

- name: Add default keyring to prevent gnome dialog (1/2)
  become: true
  template:
    src: templates/keyrings/Default_keyring.keyring
    dest: /home/play/.local/share/keyrings/Default_keyring.keyring
    owner: play
    group: play

- name: Add default keyring to prevent gnome dialog (2/2)
  become: true
  template:
    src: templates/keyrings/default
    dest: /home/play/.local/share/keyrings/default
    owner: play
    group: play

- name: Simulate Chromium first run (1/2)
  become: true
  file:
    path: /home/play/.config/chromium
    owner: play
    group: play
    state: directory

- name: Simulate Chromium first run (2/2)
  become: true
  file:
    path: "/home/play/.config/chromium/First Run"
    owner: play
    group: play
    state: touch

- name: Ensure ~/.config/autostart directory exists
  become: true
  file:
    path: /home/play/.config/autostart
    owner: play
    group: play
    state: directory

- name: Autostart play-kiosk
  become: true
  template:
    src: templates/play-kiosk.desktop
    dest: /home/play/.config/autostart/play-kiosk.desktop
    owner: play
    group: play

- name: Ensure /etc/lightdm/lightdm.conf.d directory exists
  become: true
  file:
    path: /etc/lightdm/lightdm.conf.d
    state: directory

- name: Enable auto login in lightdm
  become: true
  template:
    src: templates/50-play-autologin.conf
    dest: /etc/lightdm/lightdm.conf.d/50-play-autologin.conf

- name: Enable auto login in gdm
  become: true
  template:
    src: templates/custom.conf
    dest: /etc/gdm3/custom.conf
  ignore_errors: true

- name: Add PAM rule to allow passwordless login in GDM
  become: true
  lineinfile:
    insertbefore: BOF
    path: /etc/pam.d/gdm-password
    line: auth sufficient pam_succeed_if.so user ingroup nopasswdlogin
    state: present
  ignore_errors: true

- name: Disable apport
  become: true
  systemd:
    name: apport
    state: stopped
    enabled: no
    masked: yes
  # This may fail during setup as state is unknown
  ignore_errors: true

