- name: Add play user
  become: true
  user:
    name: play
    comment: "Dividat Play"
    groups: nopasswdlogin

- name: Install Chromium
  become: true
  apt:
    name: chromium-browser

- name: Ensure ~/bin directory exists
  become: true
  file:
    path: /home/play/bin/
    owner: play
    group: play
    state: directory

- name: Add play-kiosk script
  become: true
  template:
    src: templates/play-kiosk.sh
    dest: /home/play/bin/play-kiosk.sh
    owner: play
    group: play
    mode: u+x

- name: Ensure ~/.config/autostart directory exists
  become: true
  file:
    path: /home/play/.config/autostart
    owner: play
    group: play
    state: directory

- name: Autostart play-kiosk
  become: true
  template:
    src: templates/play-kiosk.desktop
    dest: /home/play/.config/autostart/play-kiosk.desktop
    owner: play
    group: play

- name: Ensure /etc/lightdm/lightdm.conf.d directory exists
  become: true
  file:
    path: /etc/lightdm/lightdm.conf.d
    state: directory

- name: Enable auto login
  become: true
  template:
    src: templates/50-play-autologin.conf
    dest: /etc/lightdm/lightdm.conf.d/50-play-autologin.conf
