- name: Install git
  become: true
  apt:
    name: git

- name: Ensure user exists
  user:
    name: "{{ user }}"

- name: Get nvm
  become: true
  become_user: "{{ user }}"
  git:
    repo: https://github.com/creationix/nvm.git
    dest: "{{ nvm_dir }}"
    version: "{{ nvm_version }}"


# This adds nvm to bashrc for the case that manual intervention is necessary (ansilbe does not source bashrc)
- name: Add nvm to bashrc
  become: true
  become_user: "{{ user }}"
  blockinfile:
    dest: "/home/{{ user }}/.bashrc"
    block: |
      export NVM_DIR="{{ nvm_dir }}"
      [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm


- name: Install node
  become: true
  become_user: "{{ user }}"
  environment:
    NVM_DIR: "{{ nvm_dir }}"
  shell: >
    . {{ nvm }} &&
    nvm install {{ node_version }} &&
    nvm use {{ node_version }}

- name: Install global npm dependencies
  become: true
  become_user: "{{ user }}"
  environment:
    NVM_DIR: "{{ nvm_dir }}"
  shell: >
    . {{ nvm }} &&
    npm install -g yarn pm2

- name: Get driver
  become: true
  become_user: "{{ user }}"
  git:
    repo: https://github.com/dividat/driver.git
    dest: "{{ driver_dir }}"
    version: "{{ version }}"

# TODO: fix bug in dependencies that makes yarn fail without running `npm install` first
- name: Install driver dependencies
  become: true
  become_user: "{{ user }}"
  environment:
    NVM_DIR: "{{ nvm_dir }}"
  shell: >
    . {{ nvm }} &&
    cd {{ driver_dir }} &&
    npm install --production

- name: Create pm2 process file
  become: true
  become_user: "{{ user }}"
  template:
    src: templates/config.js.j2
    dest: "{{ driver_dir }}/pm2.config.js"

- name: Start or reload process
  become: true
  become_user: "{{ user }}"
  environment:
    NVM_DIR: "{{ nvm_dir }}"
  shell: >
    . {{ nvm }} &&
    pm2 startOrReload {{ driver_dir }}/pm2.config.js &&
    pm2 save

- name: pm2 startup
  become: true
  shell: >
    env PATH=$PATH:{{ nvm_dir }}/versions/node/{{ node_version }}/bin {{ nvm_dir }}/versions/node/{{ node_version }}/lib/node_modules/pm2/bin/pm2 startup systemd -u {{ user }} --hp /home/{{ user }}

- name: Make sure ~/bin/ directory exists
  become: true
  become_user: "{{ user }}"
  file:
    path: /home/{{ user }}/bin/
    state: directory

- name: Template script to setup Network Manager connections
  become: true
  become_user: "{{ user }}"
  template:
    src: templates/setup-nm-connections.sh
    dest: /home/{{ user }}/bin/setup-nm-connections.sh
    mode: "ugo+x"

- name: Setup Network Manager connections
  become: true
  shell:
    /bin/bash /home/{{ user }}/bin/setup-nm-connections.sh
  # This will fail during installation
  ignore_errors: true

- name: Setup Network Manager connections on reboot
  become: true
  cron:
    name: "setup Network Manager connections"
    special_time: reboot
    state: present
    job: /bin/sleep 35 ; /home/{{ user }}/bin/setup-nm-connections.sh

- name: Add localhost.dividat.com to /etc/hosts
  become: true
  lineinfile:
    path: /etc/hosts
    line: '127.0.0.1 localhost.dividat.com'
