- name: Ensure user exists
  user:
    name: "{{ user }}"

- name: Stop PM2 process
  become: true
  become_user: "{{ user }}"
  command: pm2 stop all
  ignore_errors: yes

- name: Delete PM2 processes
  become: true
  become_user: "{{ user }}"
  command: pm2 delete all
  ignore_errors: yes

- name: pm2 unstartup
  become: true
  shell: >
    env PATH=$PATH:{{ nvm_dir }}/versions/node/{{ node_version }}/bin {{ nvm_dir }}/versions/node/{{ node_version }}/lib/node_modules/pm2/bin/pm2 unstartup systemd -u {{ user }} --hp /home/{{ user }}
  ignore_errors: yes

- name: Install pcscd
  become: true
  apt:
    name: pcscd

- name: Enable and start pcscd service
  become: true
  systemd:
    name: pcscd
    state: restarted
    enabled: true
  # May fail during preseed
  ignore_errors: true

- name: Remove driver directory
  become: true
  file:
    path: "{{ driver_dir }}"
    state: absent

- name: Make sure ~/bin/ directory exists
  become: true
  become_user: "{{ user }}"
  file:
    path: /home/{{ user }}/bin/
    state: directory

- name: Install curl
  become: true
  apt:
    name: curl

- name: Get latest version of driver
  become: true
  become_user: "{{ user }}"
  command: curl https://dist.dividat.com/releases/driver2/{{ driver_channel }}/latest
  register: driver_latest_version

- name: Download driver
  become: true
  become_user: "{{ user }}"
  get_url:
    url: https://dist.dividat.com/releases/driver2/{{ driver_channel }}/{{ driver_latest_version.stdout }}/dividat-driver-linux-amd64-{{ driver_latest_version.stdout }}
    dest: /home/{{ user }}/bin/dividat-driver
    force: yes
    mode: u+x

- name: Template systemd unit file
  become: true
  template:
    src: templates/dividat-driver.service.j2
    dest: /etc/systemd/system/dividat-driver.service

- name: Enable and start dividat-driver
  become: true
  systemd:
    name: dividat-driver
    state: restarted
    enabled: true
  # May fail during preseed
  ignore_errors: true

- name: Template script to setup Network Manager connections
  become: true
  become_user: "{{ user }}"
  template:
    src: templates/setup-nm-connections.sh
    dest: /home/{{ user }}/bin/setup-nm-connections.sh
    mode: "ugo+x"

- name: Setup Network Manager connections
  become: true
  shell:
    /bin/bash /home/{{ user }}/bin/setup-nm-connections.sh
  # This will fail during installation
  ignore_errors: true

- name: Setup Network Manager connections on reboot
  become: true
  cron:
    name: "setup Network Manager connections"
    special_time: reboot
    state: present
    job: /bin/sleep 35 ; /home/{{ user }}/bin/setup-nm-connections.sh

- name: Add localhost.dividat.com to /etc/hosts
  become: true
  lineinfile:
    name: /etc/hosts
    line: '127.0.0.1 localhost.dividat.com'
